import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

/*
//. The reasons for adopting app routing
Header, Footer, Navbar같은 layout을 제외한 나머지 부분만 
렌더하고 싶은데 page기반 라우팅에선 그게 문제가 있더라. 
*/
